wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.29
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.5
      5: 0.10.29
      8:
      - 5
algo:
  desc: null
  value: ppo
alpha:
  desc: null
  value: 0.99
clip_param:
  desc: null
  value: 0.2
config:
  desc: null
  value: configs/simple-key-1.json
cuda:
  desc: null
  value: false
cuda_deterministic:
  desc: null
  value: false
dice_epoch:
  desc: null
  value: 4
dice_lambda:
  desc: null
  value: 0.95
dice_task:
  desc: null
  value: null
direction:
  desc: null
  value: 0
entropy_coef:
  desc: null
  value: 0.01
env_config:
  desc: null
  value: null
env_name:
  desc: null
  value: simple-key
episode_steps:
  desc: null
  value: 50
eps:
  desc: null
  value: 1.0e-05
eval_interval:
  desc: null
  value: null
exploration_reward_alpha:
  desc: null
  value: 1.0
exploration_reward_annealing_schedule:
  desc: null
  value: null
exploration_threshold:
  desc: null
  value: null
fine_tune_start_iter:
  desc: null
  value: null
full_intrinsic:
  desc: null
  value: false
gae_lambda:
  desc: null
  value: 0.95
gail:
  desc: null
  value: false
gail_batch_size:
  desc: null
  value: 128
gail_epoch:
  desc: null
  value: 5
gail_experts_dir:
  desc: null
  value: ./gail_experts
gamma:
  desc: null
  value: 0.99
gif:
  desc: null
  value: false
guided_updates:
  desc: null
  value: 0
interpolate_rewards:
  desc: null
  value: true
likelihood_alpha:
  desc: null
  value: 0.01
likelihood_cap:
  desc: null
  value: null
likelihood_gamma:
  desc: null
  value: 0.995
likelihood_threshold:
  desc: null
  value:
  - -40.0
load:
  desc: null
  value: false
load_dir:
  desc: null
  value: ./results/stag-hunt-gw/2020-12-09T17:22:49.027992
load_step:
  desc: null
  value: null
log_dir:
  desc: null
  value: /tmp/gym/
log_interval:
  desc: null
  value: 10
log_level:
  desc: null
  value: info
lr:
  desc: null
  value: 0.001
max_grad_norm:
  desc: null
  value: 0.5
no_cuda:
  desc: null
  value: true
no_exploration_rewards:
  desc: null
  value: true
no_grad_norm_clip:
  desc: null
  value: false
no_load_refs:
  desc: null
  value: false
num_agents:
  desc: null
  value: 1
num_env_steps:
  desc: null
  value: 2560000
num_games_after_training:
  desc: null
  value: 100
num_mini_batch:
  desc: null
  value: 4
num_processes:
  desc: null
  value: 64
num_refs:
  desc: null
  value: null
num_steps:
  desc: null
  value: 100
parallel_limit:
  desc: null
  value: 64
play:
  desc: null
  value: true
plot:
  desc: null
  value: false
plot_joint_plot:
  desc: null
  value: false
ppo_epoch:
  desc: null
  value: 4
ppo_use_reference:
  desc: null
  value: false
prediction_reward_alpha:
  desc: null
  value: 0.0
recurrent_policy:
  desc: null
  value: false
ref_config:
  desc: null
  value: ./ref-configs/simple-key-1.json
ref_load_dir:
  desc: null
  value: null
ref_load_step:
  desc: null
  value: null
ref_num_ref:
  desc: null
  value: null
reject_sampling:
  desc: null
  value: false
render:
  desc: null
  value: false
reseed_step:
  desc: null
  value: -1
reseed_z:
  desc: null
  value: 7
reward_multiplier:
  desc: null
  value: 1.0
reward_normalization:
  desc: null
  value: false
reward_prediction_loss_coef:
  desc: null
  value: 1.0
reward_prediction_multiplier:
  desc: null
  value: 5.0
save_dir:
  desc: null
  value: ./sync-results/simple-key/default/1-test
save_interval:
  desc: null
  value: 100
seed:
  desc: null
  value: 1240
task:
  desc: null
  value: null
test_branching_name:
  desc: null
  value: test-branching
test_episode_steps:
  desc: null
  value: null
threshold_annealing_schedule:
  desc: null
  value: null
train:
  desc: null
  value: true
train_in_turn:
  desc: null
  value: false
use_attention:
  desc: null
  value: false
use_dynamic_prediction_alpha:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
use_likelihood_reward_cap:
  desc: null
  value: false
use_linear:
  desc: null
  value: false
use_linear_lr_decay:
  desc: null
  value: false
use_proper_time_limits:
  desc: null
  value: false
use_reference:
  desc: null
  value: true
use_reward_predictor:
  desc: null
  value: true
use_symmetry_for_reference:
  desc: null
  value: false
use_wandb:
  desc: null
  value: true
value_loss_coef:
  desc: null
  value: 1.0
wandb_group:
  desc: null
  value: default-1-test
wandb_project:
  desc: null
  value: diversity-simple-key
